name: Build ROS package

on:
  push:
    branches: [main]

jobs:
  build-package:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros-distro: melodic
            ros-version: 1
          - ros-distro: noetic
            ros-version: 1
          - ros-distro: dashing
            ros-version: 2
          - ros-distro: eloquent
            ros-version: 2
          - ros-distro: foxy
            ros-version: 2
          - ros-distro: galactic
            ros-version: 2
          - ros-distro: humble
            ros-version: 2
          - ros-distro: iron
            ros-version: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --build-arg ROS_DISTRO=${{ matrix.ros-distro }} --build-arg ROS_VERSION=${{ matrix.ros-version }} .
